version: '3'

services:

  application:
    image: amo-handler
    container_name: amo-fastapi

    depends_on:
      - redis
    build:
      context: ./
    command: uvicorn lead_orchestrator.main:app --proxy-headers --host localhost --port 5000
    volumes:
      - .:/app
    env_file:
      - .env
    restart: always
    environment:
      REDIS_HOST: redis

  redis:
    image: 'redis:7.0.5'
    container_name: redis

    volumes:
      - .services/redis/redis-data:/var/lib/redis
      - .services/redis/redis.conf:/usr/local/etc/redis/redis.conf
